name: draw_straight_line_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  auto_route: ^10.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  morphable_shape: ^2.0.0
  provider: ^6.1.5
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
